"""Carte complète du restaurant - seed unique au démarrage."""

# Structure: chaque catégorie a une couleur et une liste d'items.
# Un item peut avoir des "option_groups": [{"name": "Cuisson", "type": "single"|"multi", "required": bool, "choices": [...], "price_delta": float}]

MENU = [
    # ============== APÉRITIFS ==============
    {
        "key": "aperitifs",
        "name": "Apéritifs",
        "color": "aperitifs_tapas",
        "icon": "wine",
        "items": [
            {"name": "Martini", "price": 6.70, "unit": "6cl", "option_groups": [{"name": "Couleur", "type": "single", "required": True, "choices": ["Rouge", "Blanc"]}]},
            {"name": "Porto", "price": 6.70, "unit": "6cl", "option_groups": [{"name": "Couleur", "type": "single", "required": True, "choices": ["Rouge", "Blanc"]}]},
            {"name": "Suze", "price": 4.50, "unit": "6cl"},
            {"name": "Ricard", "price": 5.50, "unit": "3cl"},
            {"name": "Pastis Henri Bardouin", "price": 7.80, "unit": "4cl"},
            {"name": "Whisky Monkey Shoulder", "price": 8.50, "unit": "4cl"},
            {"name": "Whisky Ouiski", "price": 8.50, "unit": "4cl"},
            {"name": "Whisky Jaak Hepp", "price": 8.50, "unit": "4cl"},
            {"name": "Whisky Jack Daniel's", "price": 9.50, "unit": "4cl"},
            {"name": "Whisky Togouchi", "price": 9.90, "unit": "4cl"},
            {"name": "Whisky Scarabus", "price": 6.80, "unit": "4cl"},
            {"name": "Rhum Havana Club 3 ans", "price": 7.50, "unit": "4cl"},
            {"name": "Rhum Havana Club 5 ans", "price": 8.90, "unit": "4cl"},
            {"name": "Rhum Clément 10 ans", "price": 7.50, "unit": "4cl"},
            {"name": "Vodka Wyborowa", "price": 7.50, "unit": "4cl"},
            {"name": "Gin Hendrick's", "price": 8.50, "unit": "4cl"},
            {"name": "Gin Le Mans Coqlicorne", "price": 9.50, "unit": "4cl"},
            {"name": "Gin 501 Coqlicorne", "price": 8.50, "unit": "4cl"},
            {"name": "Gin Monkey 47", "price": 6.80, "unit": "4cl"},
            {"name": "Kir", "price": 6.80, "unit": "12cl", "option_groups": [{"name": "Parfum", "type": "single", "required": True, "choices": ["Cassis", "Mûre", "Pêche", "Framboise"]}]},
            {"name": "Kir Crémant", "price": 8.80, "unit": "12cl", "option_groups": [{"name": "Parfum", "type": "single", "required": True, "choices": ["Cassis", "Mûre", "Pêche", "Framboise"]}]},
            {"name": "Kir Royal Champagne", "price": 12.50, "unit": "12cl"},
            {"name": "Rhum arrangé Marque Noire", "price": 6.00, "unit": "4cl", "option_groups": [{"name": "Parfum", "type": "single", "required": True, "choices": ["Fraise fève de Tonka", "Orange café", "Concombre menthe"]}]},
        ],
    },
    # ============== TAPAS ==============
    {
        "key": "tapas",
        "name": "Tapas & Délices salés",
        "color": "aperitifs_tapas",
        "icon": "restaurant",
        "items": [
            {"name": "Bocaux à tartiner", "price": 10.90, "option_groups": [{"name": "Choix", "type": "single", "required": True, "choices": ["Terrine Canard Provençale", "Terrine Lapin Coteaux du Layon", "Terrine Volaille Morilles", "Rillettes Bœuf graisse canard", "Rillettes d'Anjou pur porc", "Crémeux Céleri Gorgonzola", "Tartinable Asperge Verte Parmesan", "Rillettes Chorizo", "Terrine Porc Ail des Ours", "Tartinable Deux Saumons", "Tartinable Maquereaux Moutarde"]}]},
            {"name": "Saucisson sec au choix", "price": 6.90, "unit": "150g", "option_groups": [{"name": "Parfum", "type": "single", "required": True, "choices": ["Nature", "Poivre", "Piment d'Espelette", "Noisettes", "Ail des ours", "Chèvre", "Comté"]}]},
            {"name": "Duo à Tartiner de saison", "price": 8.80, "option_groups": [{"name": "Choix (2)", "type": "multi", "required": True, "max": 2, "choices": ["Poivrons confits", "Tomates confites", "Houmous patates douces curry", "Houmous betteraves"]}]},
            {"name": "Rillauds d'Anjou", "price": 8.00},
            {"name": "Frites maison", "price": 5.30},
            {"name": "Ardoise", "price": 19.50, "option_groups": [{"name": "Type", "type": "single", "required": True, "choices": ["Charcuterie", "Fromages", "Mixte"]}]},
        ],
    },
    # ============== ENTRÉES ==============
    {
        "key": "entrees",
        "name": "Entrées",
        "color": "entrees",
        "icon": "leaf",
        "items": [
            {"name": "Salade César", "price": 19.00},
            {"name": "Burrata, Tomates marinées", "price": 14.00},
            {"name": "Ceviche de Saumon", "price": 15.00},
            {"name": "Crémeux Petits Pois Pistache", "price": 14.00},
            {"name": "Carpaccio de Bœuf", "price": 16.00},
        ],
    },
    # ============== PLATS ==============
    {
        "key": "plats",
        "name": "Plats",
        "color": "plats",
        "icon": "flame",
        "items": [
            {"name": "Moules", "price": 21.00, "option_groups": [{"name": "Sauce", "type": "single", "required": True, "choices": ["Marinière", "Curry doux", "Gorgonzola", "Provençale"]}]},
            {"name": "Saumon Teriyaki", "price": 26.00},
            {"name": "Entrecôte beurre ail estragon", "price": 28.00, "option_groups": [{"name": "Cuisson", "type": "single", "required": True, "choices": ["Bleu", "Saignant", "À point", "Bien cuit"]}]},
            {"name": "Tartare de bœuf classique", "price": 23.00, "option_groups": [{"name": "Préparation", "type": "single", "required": True, "choices": ["Froid", "Aller-retour", "Poêlé"]}]},
            {"name": "Burger poulet croustillant", "price": 21.00},
            {"name": "Suprême de volaille", "price": 26.00},
            {"name": "Gnocchi parmesan petits pois", "price": 18.00},
            {"name": "Menu Enfant", "price": 12.00, "option_groups": [{"name": "Plat", "type": "single", "required": True, "choices": ["Steak", "Poisson pané"]}, {"name": "Accompagnement", "type": "single", "required": True, "choices": ["Frites maison", "Légumes de saison"]}]},
        ],
    },
    # ============== DESSERTS ==============
    {
        "key": "desserts",
        "name": "Desserts",
        "color": "desserts",
        "icon": "ice-cream",
        "items": [
            {"name": "Assiette de Fromages", "price": 10.00, "option_groups": [{"name": "Supplément", "type": "single", "required": False, "choices": ["Sans", "Verre de vin du moment (+5€)"]}]},
            {"name": "Le Passion d'Or", "price": 13.00},
            {"name": "Le Stick Chocolat", "price": 11.00},
            {"name": "La Tarte Citron Moderne", "price": 12.00},
            {"name": "Crémet d'Anjou Caramel", "price": 10.00},
            {"name": "Café Gourmand", "price": 10.00},
            {"name": "Thé Gourmand", "price": 12.00},
            {"name": "Digestif Gourmand", "price": 15.00},
            {"name": "Glaces - 1 boule", "price": 4.00, "option_groups": [{"name": "Parfum", "type": "single", "required": True, "choices": ["Vanille", "Chocolat", "Caramel beurre salé", "Noix de coco", "Fraise", "Poire", "Citron", "Noisette", "Pistache", "Pâte à tartiner", "Yaourt des Alpes"]}, {"name": "Chantilly", "type": "single", "required": False, "choices": ["Sans", "Avec (+1,50€)"]}]},
            {"name": "Glaces - 2 boules", "price": 6.00, "option_groups": [{"name": "Parfums (2)", "type": "multi", "required": True, "max": 2, "choices": ["Vanille", "Chocolat", "Caramel beurre salé", "Noix de coco", "Fraise", "Poire", "Citron", "Noisette", "Pistache", "Pâte à tartiner", "Yaourt des Alpes"]}, {"name": "Chantilly", "type": "single", "required": False, "choices": ["Sans", "Avec (+1,50€)"]}]},
            {"name": "Glaces - 3 boules", "price": 8.00, "option_groups": [{"name": "Parfums (3)", "type": "multi", "required": True, "max": 3, "choices": ["Vanille", "Chocolat", "Caramel beurre salé", "Noix de coco", "Fraise", "Poire", "Citron", "Noisette", "Pistache", "Pâte à tartiner", "Yaourt des Alpes"]}, {"name": "Chantilly", "type": "single", "required": False, "choices": ["Sans", "Avec (+1,50€)"]}]},
            {"name": "Pot Manufacture Belles Glaces", "price": 5.70, "unit": "120ml", "option_groups": [{"name": "Parfum", "type": "single", "required": True, "choices": ["Vanille Bourbon", "Chocolat Tanzanie", "Caramel sel Guérande", "Barbe à Papa", "Fraise Senga", "Mangue Indes", "Citron vert Amériques"]}]},
        ],
    },
    # ============== BOISSONS FRAÎCHES ==============
    {
        "key": "boissons_fraiches",
        "name": "Boissons fraîches",
        "color": "boissons",
        "icon": "water",
        "items": [
            {"name": "Sirop à l'eau", "price": 3.00, "unit": "25cl", "option_groups": [{"name": "Parfum sirop", "type": "single", "required": True, "choices": ["Grenadine", "Menthe", "Pêche", "Fraise", "Citron", "Framboise", "Cerise", "Cassis", "Mûre", "Banane", "Kiwi", "Orgeat"]}]},
            {"name": "Diabolo", "price": 4.50, "unit": "25cl", "option_groups": [{"name": "Parfum sirop", "type": "single", "required": True, "choices": ["Grenadine", "Menthe", "Pêche", "Fraise", "Citron", "Framboise", "Cerise", "Cassis", "Mûre", "Banane", "Kiwi", "Orgeat"]}]},
            {"name": "Orangina", "price": 4.50, "unit": "25cl"},
            {"name": "Ice tea", "price": 4.50, "unit": "25cl"},
            {"name": "Oasis Tropical", "price": 4.50, "unit": "25cl"},
            {"name": "Schweppes", "price": 4.50, "unit": "25cl", "option_groups": [{"name": "Type", "type": "single", "required": True, "choices": ["Agrum", "Tonic"]}]},
            {"name": "Limonade Fizz Bio", "price": 4.70, "unit": "33cl"},
            {"name": "Coca-Cola", "price": 4.70, "unit": "33cl", "option_groups": [{"name": "Type", "type": "single", "required": True, "choices": ["Coca-Cola", "Coca-Cola Zéro"]}]},
            {"name": "Red Bull", "price": 5.00, "unit": "25cl"},
            {"name": "Jus Granini", "price": 4.50, "unit": "25cl", "option_groups": [{"name": "Parfum", "type": "single", "required": True, "choices": ["Orange", "Ananas", "Abricot", "Pomme", "Tomate", "ACE"]}]},
            {"name": "Carafe d'eau filtrée", "price": 1.50, "unit": "75cl"},
            {"name": "Carafe d'eau gazéifiée", "price": 3.00, "unit": "75cl"},
            {"name": "Evian", "price": 5.20, "unit": "75cl"},
            {"name": "Vittel", "price": 3.20, "unit": "25cl"},
            {"name": "Badoit", "price": 5.80, "unit": "75cl"},
            {"name": "Chateldon", "price": 6.20, "unit": "75cl"},
            {"name": "Perrier", "price": 4.00, "unit": "33cl"},
        ],
    },
    # ============== BOISSONS CHAUDES ==============
    {
        "key": "boissons_chaudes",
        "name": "Boissons chaudes",
        "color": "cafes_digestifs",
        "icon": "cafe",
        "items": [
            {"name": "Expresso", "price": 2.30, "option_groups": [{"name": "Type", "type": "single", "required": False, "choices": ["Normal", "Décaféiné"]}]},
            {"name": "Allongé", "price": 2.50, "option_groups": [{"name": "Type", "type": "single", "required": False, "choices": ["Normal", "Décaféiné"]}]},
            {"name": "Café noisette", "price": 2.50},
            {"name": "Double expresso", "price": 3.90},
            {"name": "Grand crème", "price": 4.20},
            {"name": "Cappuccino", "price": 4.20},
            {"name": "Chocolat chaud", "price": 4.60},
            {"name": "Grand chocolat chaud", "price": 7.10},
            {"name": "Thé Dammann", "price": 4.50, "option_groups": [{"name": "Choix", "type": "single", "required": True, "choices": ["Thé sélection", "Infusion sélection"]}]},
            {"name": "Thé glacé Filles de l'Ouest", "price": 5.20, "unit": "33cl", "option_groups": [{"name": "Type", "type": "single", "required": True, "choices": ["L'idyllique (Darjeeling menthe gingembre)", "L'extravagant (Chaï noir cannelle hibiscus)"]}]},
        ],
    },
    # ============== VINS ==============
    {
        "key": "vins_verre",
        "name": "Vins au verre",
        "color": "vins",
        "icon": "wine",
        "items": [
            {"name": "Anjou blanc Bio", "price": 5.00, "unit": "12,5cl"},
            {"name": "Savennières", "price": 7.00, "unit": "12,5cl"},
            {"name": "Sauvignon", "price": 5.50, "unit": "12,5cl"},
            {"name": "Chardonnay", "price": 5.50, "unit": "12,5cl"},
            {"name": "Coteaux du Layon", "price": 6.50, "unit": "12,5cl"},
            {"name": "Coteaux de l'Aubance", "price": 6.50, "unit": "12,5cl"},
            {"name": "Anjou rouge Bio", "price": 5.00, "unit": "12,5cl"},
            {"name": "Saumur-Champigny Bio", "price": 6.00, "unit": "12,5cl"},
            {"name": "Vin du moment", "price": 6.00, "unit": "12,5cl"},
            {"name": "Rosé de Loire Bio", "price": 5.00, "unit": "12,5cl"},
            {"name": "Côtes de Provence rosé", "price": 6.50, "unit": "12,5cl"},
            {"name": "Crémant Loire Blanc Baumard", "price": 7.50, "unit": "12cl"},
            {"name": "Crémant Loire Rosé Baumard", "price": 7.50, "unit": "12cl"},
            {"name": "Champagne Haton", "price": 12.50, "unit": "12cl"},
        ],
    },
    {
        "key": "vins_rouge",
        "name": "Vins rouges (75cl)",
        "color": "vins",
        "icon": "wine",
        "items": [
            {"name": "Anjou rouge - Cady", "price": 29.00},
            {"name": "Anjou Village - Rocca Nigra", "price": 39.00},
            {"name": "Anjou Village - Petra Alba", "price": 39.00},
            {"name": "Sancerre - Serge Laloue", "price": 45.00},
            {"name": "Saumur-Champigny - Filliatreau", "price": 38.00},
            {"name": "Saint-Nicolas Bourgueil", "price": 38.00},
            {"name": "Chinon - Ch. de la Grille", "price": 49.00},
            {"name": "Côtes du Rhône - Parallèle 45", "price": 33.00},
            {"name": "Côtes du Rhône Village - Agrioto", "price": 35.00},
            {"name": "Gigondas - Jocasses", "price": 47.00},
            {"name": "Châteauneuf-du-Pape - Mouriesse", "price": 87.00},
            {"name": "Châteauneuf-du-Pape - Clos des Papes", "price": 195.00},
            {"name": "Saint-Joseph - Chapoutier", "price": 48.00},
            {"name": "Crozes-Hermitage - Meysonniers", "price": 42.00},
            {"name": "Crozes-Hermitage - Guigal", "price": 60.00},
            {"name": "Madiran - Heritage Peyros", "price": 38.00},
            {"name": "Madiran - Ode d'Aydie", "price": 42.00},
            {"name": "Loup du Pic - Pic Saint-Loup", "price": 39.00},
            {"name": "Prestige Puech-Haut", "price": 39.00},
            {"name": "Tête de Bélier Puech-Haut", "price": 59.00},
            {"name": "Bila-Haut Chapoutier", "price": 25.00},
            {"name": "Sorcières Clos des Fées", "price": 56.00},
            {"name": "Minervois Incarnat", "price": 44.00},
            {"name": "Graves Ch. Ferrande", "price": 40.00},
            {"name": "Fronsac Ch. La Rivière", "price": 52.00},
            {"name": "Haut-Médoc Clément-Pichon", "price": 62.00},
            {"name": "Haut-Médoc Citran", "price": 68.00},
            {"name": "Haut-Médoc Sociado-Mallet", "price": 105.00},
            {"name": "Moulis Maucaillou", "price": 78.00},
            {"name": "Pessac-Léognan Solitude", "price": 80.00},
            {"name": "Margaux Paveil de Luze", "price": 80.00},
        ],
    },
    {
        "key": "vins_blanc",
        "name": "Vins blancs (75cl)",
        "color": "vins",
        "icon": "wine",
        "items": [
            {"name": "Anjou blanc - Cady", "price": 28.00},
            {"name": "Pineau de Loire - Piégué", "price": 32.00},
            {"name": "Printemps - Petits Quarts", "price": 32.00},
            {"name": "Mea Culpa - Petits Quarts", "price": 38.00},
            {"name": "Ordovicien - Bablut", "price": 39.00},
            {"name": "Âme de Piégué", "price": 45.00},
            {"name": "Savennières - La Croix Picot", "price": 38.00},
            {"name": "Savennières - Clos Saint-Yves", "price": 42.00},
            {"name": "Savennières - Clos du Papillon", "price": 54.00},
            {"name": "Chardonnay - Régnier-David", "price": 25.00},
            {"name": "Sauvignon - Régnier-David", "price": 25.00},
            {"name": "Coteaux de l'Aubance - Gagnebert", "price": 35.00},
            {"name": "Coteaux du Layon - Tentation", "price": 35.00},
            {"name": "Quincy - Préface", "price": 39.00},
            {"name": "Sancerre - Beau Roy", "price": 45.00},
            {"name": "Pouilly-Fumé - Treuillet", "price": 39.00},
            {"name": "Chablis - Camu", "price": 49.00},
            {"name": "Côtes du Rhône - Belleruche", "price": 26.00},
            {"name": "Pessac-Léognan - Carbonnieux", "price": 110.00},
            {"name": "Bourgogne - Heimbourger", "price": 38.00},
            {"name": "Hautes Côtes de Beaune", "price": 42.00},
            {"name": "Meursault - Louis Latour", "price": 79.00},
            {"name": "Retour de Piste - Mont Baudile", "price": 29.00},
            {"name": "Côtes du Roussillon Alysses", "price": 38.00},
            {"name": "La Clape Rocaille", "price": 37.00},
            {"name": "Prestige Puech-Haut", "price": 38.00},
        ],
    },
    {
        "key": "vins_rose",
        "name": "Vins rosés (75cl)",
        "color": "vins",
        "icon": "wine",
        "items": [
            {"name": "Domaine Gonorderie", "price": 26.00},
            {"name": "Domaine Cady Bio", "price": 26.00},
            {"name": "Reuilly Pinot Gris Bio", "price": 36.00},
            {"name": "Gris de la Dune", "price": 28.00},
            {"name": "Chill Puech-Haut", "price": 29.00},
            {"name": "Villa Angeli Don Pasquale", "price": 36.00},
            {"name": "Villa Angeli Mizael", "price": 45.00},
            {"name": "La Maura Fabre-Grimaldi", "price": 30.00},
            {"name": "Château des Brigands", "price": 35.00},
            {"name": "M de Minuty", "price": 38.00},
            {"name": "Prestige Minuty", "price": 44.00},
            {"name": "Château Miraval", "price": 48.00},
        ],
    },
    {
        "key": "champagnes",
        "name": "Champagnes & Crémants",
        "color": "vins",
        "icon": "wine",
        "items": [
            {"name": "Crémant Loire - Cuvée Turquoise Blanc", "price": 35.00, "unit": "75cl"},
            {"name": "Crémant Loire - Cuvée Corail Rosé", "price": 35.00, "unit": "75cl"},
            {"name": "Champagne Haton Blanc de Blancs", "price": 70.00, "unit": "75cl"},
            {"name": "Champagne Haton Magnum", "price": 140.00, "unit": "Magnum"},
            {"name": "Champagne Ruinart Brut", "price": 100.00, "unit": "75cl"},
            {"name": "Champagne Ruinart Blanc de Blanc", "price": 165.00, "unit": "75cl"},
        ],
    },
    # ============== DIGESTIFS ==============
    {
        "key": "digestifs",
        "name": "Digestifs",
        "color": "cafes_digestifs",
        "icon": "wine",
        "items": [
            {"name": "Menthe Pastille Giffard", "price": 7.50, "unit": "4cl"},
            {"name": "Cointreau", "price": 7.50, "unit": "4cl"},
            {"name": "Limoncello Villa Duca", "price": 7.50, "unit": "4cl"},
            {"name": "Get 27", "price": 7.50, "unit": "4cl"},
            {"name": "Bayleys Irish Cream", "price": 7.50, "unit": "4cl"},
            {"name": "Cognac Grande Champagne Bio 7 ans", "price": 9.80, "unit": "4cl"},
            {"name": "Amarande Giffard", "price": 7.50, "unit": "4cl"},
            {"name": "Bas Armagnac XO Laubade", "price": 9.80, "unit": "4cl"},
            {"name": "Calvados Pays d'Auge 3 ans Groult", "price": 7.50, "unit": "4cl"},
        ],
    },
]
